### PR TITLE
feat(form):Create resizable drawer 

### PR DESCRIPTION
**Pull request by natashaamin**
https://github.com/ant-design/pro-components/assets/48901325/95d23b5d-9cab-4a80-bcc4-1980c177f697

By adding new api called isResizable, user will be able to change the width of the drawer by dragging it. It gives a flexible way for user to have a better view of internal content. 

Do let me know if there i any changes need to improve. I really appreciate the afford to review it. Thank you!

### CODE REVIEW

**Comment by chenshuai2144** [comment]
我对 api  有一些疑问，我觉得这样会好一些

```tsx
resize={{
   onResize:(size)=>{}
}}

resize=false

resize={{}}
```

**Comment by natashaamin** [comment]
> 我对 api 有一些疑问，我觉得这样会好一些
> 
> ```tsx
> resize={{
>    onResize:(size)=>{}
> }}
> 
> resize=false
> 
> resize={{}}
> ```

do u still have a lot of keys inside resize? or is it only onResize?

**Comment by natashaamin** [comment]
trying to run pnpm run test:update, but i saw that some other jest test file are failing such as LightFilter, StepForm etc, but i never changed anything on those. Can you please assist me on this? @chenshuai2144 

image

**Comment by ONLY-yours** [comment]
> ## [Codecov](https://app.codecov.io/gh/ant-design/pro-components/pull/7288?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=ant-design) Report
> Patch coverage: **`63.41`**% and project coverage change: **`-0.12`** ⚠️
> 
> > Comparison is base [(`da90c1a`)](https://app.codecov.io/gh/ant-design/pro-components/commit/da90c1a65b96be301f872ae8d91198e4d76aa11f?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=ant-design) 97.98% compared to head [(`ce5af9e`)](https://app.codecov.io/gh/ant-design/pro-components/pull/7288?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=ant-design) 97.86%.
> 
> > ❗ Current head [ce5af9e](https://github.com/ant-design/pro-components/commit/ce5af9e57429f7e6f9fd9f9bd91281f12ac7590f) differs from pull request most recent head [e759a90](https://github.com/ant-design/pro-components/commit/e759a90741e96fda6210285263892f77890002f6). Consider uploading reports for the commit [e759a90](https://github.com/ant-design/pro-components/commit/e759a90741e96fda6210285263892f77890002f6) to get more accurate results
> 
> Additional details and impacted files
> [☔ View full report in Codecov by Sentry](https://app.codecov.io/gh/ant-design/pro-components/pull/7288?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=ant-design). 📢 Do you have feedback about the report comment? [Let us know in this issue](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=ant-design).

@natashaamin  can you add some unit test about it, coverage was a little updown

**Comment by chenshuai2144** [comment]
Currently, there is only 'onResize' available, but in the future, there might be additional features added, such as maximum width and minimum width.

@natashaamin

**Comment by natashaamin** [comment]
> Currently, there is only 'onResize' available, but in the future, there might be additional features added, such as maximum width and minimum width.
> 
> @natashaamin

Tried to do as what you suggestion. Can you help me take a look into it please? Thank you.

**Comment by chenshuai2144** [comment]
👌

**Pull request merged**
